#!/bin/bash
if [ "$(stat -c %U hello)" = "guillaume" ]; then
    sudo chown vincent hello
    echo "Owner changed to vincent."
else
    echo "The file 'hello' is not owned by guillaume. No changes made."
fi
